Repository DeveloperAcademy-POSTECH/2024-MacC-M11-1Byte, pull requests merged in 2024-12, with the labels that each got.

#120 [Mars/Feat/#117]  클로버카드 완수율 및 앱 첫주차 날짜 매칭 실패 문제
  OneByte/Resource/Assets.xcassets/Color/my505050.colorset/Contents.json
  OneByte/Source/Extension/Date+.swift
  OneByte/Source/Features/Routine/VM/TodayRoutineViewModel.swift
  OneByte/Source/Features/Routine/View/CloverCardView.swift
Labels: Fix

#122 [Mars/Fix/#121] 초기화 날짜 없을때, 클로버 카드뷰가 뜨는 이슈
  OneByte.xcodeproj/project.pbxproj
  OneByte/Source/Application/TabBarManager.swift
  OneByte/Source/Application/WeeklyResetManager.swift
Labels: Fix

#124 [Vinci/Fix/#106] 멘트 수정
  OneByte/Source/Features/Statistics/ViewModel/StatisticViewModel.swift
Labels: Fix

#127 [Vinci/Fix/#126] 통계 뷰 12월 마지막 주차 이슈해결
  OneByte/Source/Features/Statistics/View/StatisticView.swift
  OneByte/Source/Features/Statistics/ViewModel/StatisticViewModel.swift
Labels: Fix

#132 [Mars/Fix/#128] 카테고리 없을시 완수율에서 표시 수정 및 디테일 수정
  OneByte/Resource/Assets.xcassets/Color/myB2AFAA.colorset/Contents.json
  OneByte/Source/Application/TabBarManager.swift
  OneByte/Source/Application/WeeklyResetManager.swift
  OneByte/Source/Features/Onboarding/View/DaysCycleView.swift
  OneByte/Source/Features/Onboarding/ViewModel/RoutineCycleViewModel.swift
  OneByte/Source/Features/Routine/VM/RoutineMainViewModel.swift
  OneByte/Source/Features/Routine/View/CloverCardView.swift
  OneByte/Source/Features/Routine/View/RoutineMainView.swift
  OneByte/Source/Features/Setting/View/SettingView.swift
Labels: Fix

#136 [Vinci/Design/#134] 통계뷰 주차 클로버 배경 수정
  OneByte/Source/Features/Statistics/View/StatisticView.swift
  OneByte/Source/Features/Statistics/ViewModel/StatisticViewModel.swift
Labels: Design

#138 [Mars/Design/#137] 클로버카드 완수율 레이아웃 수정
  OneByte/Source/Features/Routine/View/CloverCardView.swift
Labels: Design

#143 [Realese] 하고만다 ver 1.1.0 (4) 업데이트
  OneByte.xcodeproj/project.pbxproj
  OneByte/Source/Features/Mandalart/View/Sheet/DetailGoalView.swift
Labels: Realese

#148 [Mars/Feat/#146] 루틴뷰 만부기 로티 추가 및 디자인 디테일 수정
  OneByte.xcodeproj/project.pbxproj
  OneByte/Resource/Assets.xcassets/Onboarding/OnboardingTurtle1.imageset/OnboardingTurtle1.png
  OneByte/Resource/Assets.xcassets/Onboarding/OnboardingTurtle1.imageset/OnboardingTurtle1@2x.png
  OneByte/Resource/Assets.xcassets/Onboarding/OnboardingTurtle1.imageset/OnboardingTurtle1@3x.png
  OneByte/Resource/MandalartTurtle.json
  OneByte/Resource/RoutineTurtle.json
  OneByte/Source/Features/Onboarding/Cell/DaysCycleCell.swift
  OneByte/Source/Features/Onboarding/View/DaysCycleView.swift
  OneByte/Source/Features/Onboarding/View/RoutineCycleView.swift
  OneByte/Source/Features/Routine/VM/RoutineMainViewModel.swift
  OneByte/Source/Features/Routine/View/RoutineMainView.swift
  OneByte/Source/Features/Routine/View/TodayRoutineView.swift
  OneByte/Source/Helper/RoutineTurtleLottie.swift
  OneByte/Source/Helper/TurtleMessageView.swift
Labels: Feat

#152 [Mars/Fix/#151] 기타 카테고리 버그 수정
  OneByte/Source/Features/Mandalart/View/Sheet/SubGoalView.swift
Labels: Fix

#153 [Vinci/Fix/#144] 통계뷰 물음표 말풍선 수정 및 ML 성능 개선
  OneByte.xcodeproj/project.pbxproj
  OneByte/Resource/SpecificTagger4342.mlmodel
  OneByte/Resource/SpecificTagger4967.mlmodel
  OneByte/Resource/SpecificTagger5267.mlmodel
  OneByte/Resource/SpecificTagger6342.mlmodel
  OneByte/Source/Features/Mandalart/MandalartViewModel.swift
  OneByte/Source/Features/Statistics/View/StatisticView.swift
Labels: Fix

#154 [Realese] 하고만다 ver 1.1.1 업데이트
  OneByte.xcodeproj/project.pbxproj
  OneByte/Resource/Assets.xcassets/Color/my235223.colorset/Contents.json
  OneByte/Resource/Assets.xcassets/Color/my887B6D.colorset/Contents.json
  OneByte/Resource/Assets.xcassets/Onboarding/OnboardingTurtle1.imageset/OnboardingTurtle1.png
  OneByte/Resource/Assets.xcassets/Onboarding/OnboardingTurtle1.imageset/OnboardingTurtle1@2x.png
  OneByte/Resource/Assets.xcassets/Onboarding/OnboardingTurtle1.imageset/OnboardingTurtle1@3x.png
  OneByte/Resource/Assets.xcassets/Onboarding/hifi.imageset/Contents.json
  OneByte/Resource/Assets.xcassets/Onboarding/hifi.imageset/Group 661.png
  OneByte/Resource/Assets.xcassets/Onboarding/hifi.imageset/Group 661@2x.png
  OneByte/Resource/Assets.xcassets/Onboarding/hifi.imageset/Group 661@3x.png
  OneByte/Resource/MandalartTurtle.json
  OneByte/Resource/RoutineTurtle.json
  OneByte/Resource/SpecificTagger4342.mlmodel
  OneByte/Resource/SpecificTagger4967.mlmodel
  OneByte/Resource/SpecificTagger5267.mlmodel
  OneByte/Resource/SpecificTagger6342.mlmodel
  OneByte/Source/Features/Mandalart/MandalartViewModel.swift
  OneByte/Source/Features/Mandalart/View/MandalartView.swift
  OneByte/Source/Features/Mandalart/View/Sheet/DetailGoalView.swift
  OneByte/Source/Features/Mandalart/View/Sheet/SubGoalView.swift
  OneByte/Source/Features/Onboarding/Cell/DaysCycleCell.swift
  OneByte/Source/Features/Onboarding/View/DaysCycleView.swift
  OneByte/Source/Features/Onboarding/View/RoutineCycleView.swift
  OneByte/Source/Features/Routine/VM/RoutineMainViewModel.swift
  OneByte/Source/Features/Routine/View/AllRoutineView.swift
  OneByte/Source/Features/Routine/View/RoutineMainView.swift
  OneByte/Source/Features/Routine/View/TodayRoutineView.swift
  OneByte/Source/Features/Statistics/View/StatisticView.swift
  OneByte/Source/Helper/MandalartMessageView.swift
  OneByte/Source/Helper/RoutineTurtleLottie.swift
  OneByte/Source/Helper/TurtleMessageView.swift
Labels: Realese

#156 [Trudy/Hotfix/#155] 알림 토글 꺼지지 않는 현상 해결
  OneByte.xcodeproj/project.pbxproj
  OneByte/Source/Features/Mandalart/View/Sheet/DetailGoalView.swift
Labels: Hotfix

#158 [Mars/Hotfix/#157] 클로버 카드뷰 텍스트 크기 수정
  OneByte.xcodeproj/project.pbxproj
  OneByte/Source/Features/Routine/View/CloverCardView.swift
Labels: Hotfix

#161 [Vinci/HotFix/#160] 모델 성능 긴급 조정
  OneByte.xcodeproj/project.pbxproj
  OneByte/Resource/SpecificTagger6342.mlmodel
  OneByte/Source/Features/Mandalart/MandalartViewModel.swift
Labels: Hotfix

#162 [Realese] 하고만다 ver 1.1.2 업데이트
  OneByte.xcodeproj/project.pbxproj
  OneByte/Resource/SpecificTagger6342.mlmodel
  OneByte/Source/Features/Mandalart/MandalartViewModel.swift
Labels: Realese

#164 [Hotfix] AI 모델 파일 추가
  OneByte.xcodeproj/project.pbxproj
Labels: Hotfix

#170 [Vinci/Feat/#168] 쇼케이스용 통계뷰 버튼 구현
  OneByte/Source/Features/Statistics/View/StatisticView.swift
  OneByte/Source/Features/Statistics/ViewModel/StatisticViewModel.swift
Labels: Feat

#171 [Mars/Feat/#169] 쇼케이스 루틴뷰 구현
  OneByte.xcodeproj/project.pbxproj
  OneByte/Source/Features/Onboarding/ViewModel/OnboardingStartViewModel.swift
Labels: Feat

#173 [Mars/Feat/#172] 통계뷰에서 클로버카드뷰 연결
  OneByte/Source/Application/TabBarManager.swift
  OneByte/Source/Features/Routine/View/CloverCardView.swift
  OneByte/Source/Features/Statistics/View/StatisticView.swift
Labels: Feat

#179 [Trudy/Feat/#176] 쇼케이스용 삭제기능 추가
  OneByte.xcodeproj/project.pbxproj
  OneByte/Source/Features/Mandalart/MandalartViewModel.swift
  OneByte/Source/Features/Mandalart/View/MandalartView.swift
  OneByte/Source/Features/Routine/Cell/SpecificTagger4192.mlmodel
  OneByte/Source/UseCases/Protocol.swift
  OneByte/Source/UseCases/Services/CreateService.swift
  OneByte/Source/UseCases/Services/DeleteService.swift
Labels: Feat

#184 [Realese] 하고만다 ver 1.1.3 업데이트
  OneByte.xcodeproj/project.pbxproj
  OneByte/Source/Features/Mandalart/View/Sheet/SubGoalView.swift
Labels: Realese

#187 [Vinci/Fix/#186] 통계 뷰 월주차가 동일할 시 어느 월이든 empty 클로버로 나오는 문제
  OneByte.xcodeproj/project.pbxproj
  OneByte/Source/Features/Statistics/View/StatisticView.swift
Labels: Fix

#188 [Mars/Hotfix/#185] 루틴 진행도 클로버 그라데이션 수정
  OneByte/Source/Features/Routine/Cell/WeekAchieveCell.swift
Labels: Hotfix

#189 [Realese] 하고만다 ver 1.1.3 업데이트 (2차)
  OneByte.xcodeproj/project.pbxproj
  OneByte/Source/Features/Routine/Cell/WeekAchieveCell.swift
  OneByte/Source/Features/Statistics/View/StatisticView.swift
Labels: Realese

#190 [Chore] README
  README.md
Labels: Chore

#191 [Chore] develop <- main 병합
  LICENSE
  OneByte.xcodeproj/project.pbxproj
  README.md
Labels: Chore

#193 [Mars/Fix/#192] 오늘의 루틴뷰 수정 및 Dynamic Font Sizes 대응
  OneByte/Source/Extension/Font+.swift
  OneByte/Source/Features/Onboarding/View/SubgoalCycleView.swift
  OneByte/Source/Features/Routine/Cell/TodayRoutineCell.swift
  OneByte/Source/Features/Routine/View/TodayRoutineView.swift
Labels: Fix

#195 [Trudy/Fix/#194] 만다라트 뷰 관련 코드 showcase 버전에 맞게 수정
  OneByte.xcodeproj/project.pbxproj
  OneByte/Source/Application/Notification.swift
  OneByte/Source/Features/Mandalart/View/MandalartView.swift
  OneByte/Source/Features/Mandalart/View/Sheet/DetailGoalView.swift
  OneByte/Source/Features/Mandalart/View/Sheet/SubGoalView.swift
  OneByte/Source/UseCases/Services/CreateService.swift
  README.md
Labels: Fix

#196 [Realese] 하고만다 ver 1.1.4 업데이트
  OneByte.xcodeproj/project.pbxproj
  OneByte/Source/Application/Notification.swift
  OneByte/Source/Extension/Font+.swift
  OneByte/Source/Features/Mandalart/View/MandalartView.swift
  OneByte/Source/Features/Mandalart/View/Sheet/DetailGoalView.swift
  OneByte/Source/Features/Mandalart/View/Sheet/SubGoalView.swift
  OneByte/Source/Features/Onboarding/View/SubgoalCycleView.swift
  OneByte/Source/Features/Routine/Cell/TodayRoutineCell.swift
  OneByte/Source/Features/Routine/View/TodayRoutineView.swift
  OneByte/Source/UseCases/Services/CreateService.swift
Labels: Realese

#198 [Chore] develop <- main (1.1.4) 병합
  OneByte.xcodeproj/project.pbxproj
Labels: Chore

#201 [Mars/Fix/#200] 루틴 팝업뷰 레이아웃 수정
  OneByte.xcodeproj/project.pbxproj
  OneByte/Source/Features/Routine/VM/AllRoutineViewModel.swift
  OneByte/Source/Features/Routine/VM/RoutineMainViewModel.swift
  OneByte/Source/Features/Routine/View/AllRoutineView.swift
  OneByte/Source/Features/Routine/View/RoutineMainView.swift
  OneByte/Source/Features/Routine/View/RoutinePopUpView.swift
  OneByte/Source/Features/Routine/View/WeekRoutineView.swift
Labels: Fix

#204 [Mars/Hotfix/#203] Dynamic Font Sizes 재대응
  OneByte.xcodeproj/project.pbxproj
  OneByte/Source/Extension/Font+.swift
Labels: Hotfix

#205 [Chore] develop <- main (1.1.6) 병합
  OneByte.xcodeproj/project.pbxproj
  OneByte/Source/Extension/Font+.swift
Labels: Chore
